import type { FileSystem } from '@custom-types/file.type';
import { LockFileParser } from '../lock-file-parser';

describe('LockFileParser', () => {
  let mockFs: FileSystem;
  let parser: LockFileParser;

  beforeEach(() => {
    mockFs = {
      join: jest.fn((...paths) => paths.join('/')),
      exists: jest.fn(),
      read: jest.fn(),
    } as unknown as FileSystem;

    parser = new LockFileParser(mockFs);
  });

  describe('getVersions', () => {
    it('should return versions from package-lock.json', async () => {
      const mockPackageJson = JSON.stringify({
        name: 'test',
        dependencies: { react: '^18.0.0', next: '^13.0.0' },
      });

      const mockLockFile = JSON.stringify({
        lockfileVersion: 2,
        packages: {
          '': { name: 'test' },
          'node_modules/react': { version: '18.2.0' },
          'node_modules/next': { version: '13.4.19' },
        },
      });

      (mockFs.exists as jest.Mock).mockReturnValue(true);
      (mockFs.read as jest.Mock)
        .mockReturnValueOnce(mockPackageJson)
        .mockReturnValueOnce(mockLockFile);

      const versions = await parser.getVersions('/test/repo', ['react', 'next']);

      expect(versions.get('react')).toBe('18.2.0');
      expect(versions.get('next')).toBe('13.4.19');
      expect(versions.size).toBe(2);
    });

    it('should return single package version', async () => {
      const mockPackageJson = JSON.stringify({
        name: 'test',
        dependencies: { react: '^18.0.0' },
      });

      const mockLockFile = JSON.stringify({
        lockfileVersion: 2,
        packages: {
          '': { name: 'test' },
          'node_modules/react': { version: '18.2.0' },
        },
      });

      (mockFs.exists as jest.Mock).mockReturnValue(true);
      (mockFs.read as jest.Mock)
        .mockReturnValueOnce(mockPackageJson)
        .mockReturnValueOnce(mockLockFile);

      const versions = await parser.getVersions('/test/repo', ['react']);

      expect(versions.get('react')).toBe('18.2.0');
      expect(versions.size).toBe(1);
    });

    it('should return empty map when package not found', async () => {
      const mockPackageJson = JSON.stringify({
        name: 'test',
        dependencies: { react: '^18.0.0' },
      });

      const mockLockFile = JSON.stringify({
        lockfileVersion: 2,
        packages: {
          '': { name: 'test' },
          'node_modules/react': { version: '18.2.0' },
        },
      });

      (mockFs.exists as jest.Mock).mockReturnValue(true);
      (mockFs.read as jest.Mock)
        .mockReturnValueOnce(mockPackageJson)
        .mockReturnValueOnce(mockLockFile);

      const versions = await parser.getVersions('/test/repo', ['vue']);

      expect(versions.has('vue')).toBe(false);
      expect(versions.size).toBe(0);
    });

    it('should return empty map when lock file does not exist', async () => {
      (mockFs.exists as jest.Mock).mockReturnValue(false);

      const versions = await parser.getVersions('/test/repo', ['react']);

      expect(versions.size).toBe(0);
    });

    it('should fallback to yarn.lock when package-lock.json not found', async () => {
      const mockPackageJson = JSON.stringify({
        name: 'test',
        dependencies: { react: '^18.0.0' },
      });

      const mockYarnLock = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.0.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
`;

      (mockFs.exists as jest.Mock).mockImplementation((path: string) => {
        if (path.includes('package-lock.json')) return false;
        if (path.includes('yarn.lock')) return true;
        if (path.includes('package.json')) return true;
        return false;
      });

      (mockFs.read as jest.Mock)
        .mockReturnValueOnce(mockPackageJson)
        .mockReturnValueOnce(mockYarnLock);

      const versions = await parser.getVersions('/test/repo', ['react']);

      expect(versions.get('react')).toBe('18.2.0');
    });

    it('should handle parse errors gracefully', async () => {
      (mockFs.exists as jest.Mock).mockReturnValue(true);
      (mockFs.read as jest.Mock).mockReturnValue('invalid json');

      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();

      const versions = await parser.getVersions('/test/repo', ['react']);

      expect(versions.size).toBe(0);
      expect(consoleErrorSpy).toHaveBeenCalled();

      consoleErrorSpy.mockRestore();
    });

    it('should filter only requested packages', async () => {
      const mockPackageJson = JSON.stringify({
        name: 'test',
        dependencies: {
          react: '^18.0.0',
          next: '^13.0.0',
          vue: '^3.0.0',
        },
      });

      const mockLockFile = JSON.stringify({
        lockfileVersion: 2,
        packages: {
          '': { name: 'test' },
          'node_modules/react': { version: '18.2.0' },
          'node_modules/next': { version: '13.4.19' },
          'node_modules/vue': { version: '3.3.4' },
        },
      });

      (mockFs.exists as jest.Mock).mockReturnValue(true);
      (mockFs.read as jest.Mock)
        .mockReturnValueOnce(mockPackageJson)
        .mockReturnValueOnce(mockLockFile);

      const versions = await parser.getVersions('/test/repo', ['react', 'vue']);

      expect(versions.has('react')).toBe(true);
      expect(versions.has('vue')).toBe(true);
      expect(versions.has('next')).toBe(false);
      expect(versions.size).toBe(2);
    });
  });

  describe('custom lock file names', () => {
    it('should use custom lock file names', async () => {
      const customParser = new LockFileParser(mockFs, {
        npm: 'custom-lock.json',
      });

      (mockFs.exists as jest.Mock).mockReturnValue(false);

      await customParser.getVersions('/test/repo', ['react']);

      expect(mockFs.join).toHaveBeenCalledWith('/test/repo', 'custom-lock.json');
    });
  });
});
