/**
 * PR Comment Generator
 * Generates GitHub PR comment with analysis results
 */

import * as core from '@actions/core';
import {
  AnalysisResult,
  Issue,
  ChangesSummary,
  DestinationImpact,
  AIInsight,
  FileAnalysisInfo,
} from '../types/common';

export interface CommentOptions {
  verbosity: 'minimal' | 'standard' | 'detailed';
  includePropertyDetails: boolean;
}

/**
 * Generate complete PR comment
 */
export function generatePRComment(
  result: AnalysisResult,
  options: CommentOptions = { verbosity: 'standard', includePropertyDetails: false },
  sdkInfo?: { type: string; version?: string; methodCallsCount?: number; framework?: string }
): string {
  const sections: string[] = [];

  // Header with icon
  sections.push('## <img src="https://github.com/rudderlabs/pr-reviewer/raw/develop/icon.png" width="22" height="22" /> RudderStack Instrumentation Review\n');

  // Summary
  sections.push(generateSummary(result, sdkInfo));

  // Files Analyzed
  sections.push(generateFilesSection(result.filesAnalyzed));

  // Note about where to find detailed issues
  const errors = result.issues.filter((i) => i.severity === 'error');
  const warnings = result.issues.filter((i) => i.severity === 'warning');
  const suggestions = result.issues.filter((i) => i.severity === 'suggestion');

  if (errors.length > 0 || warnings.length > 0 || suggestions.length > 0) {
    const messages: string[] = [];
    if (errors.length > 0 || warnings.length > 0) {
      messages.push('**Errors and warnings** are shown as inline review comments on specific lines');
    }
    if (suggestions.length > 0) {
      messages.push('**Suggestions** are included in the review comment below');
    }
    sections.push(messages.join('\n\n') + '\n');
  }

  // Destination Impacts (collapsible)
  if (result.destinationImpacts && result.destinationImpacts.length > 0) {
    sections.push(generateDestinationImpactsSection(result.destinationImpacts, true));
  }

  // Changes Detected (collapsible)
  if (result.changes && hasChanges(result.changes)) {
    sections.push(generateChangesSection(result.changes, options.includePropertyDetails, true));
  }

  // AI Analysis (collapsible)
  if (result.aiInsights && result.aiInsights.length > 0) {
    sections.push(generateAIAnalysisSection(result.aiInsights, true));
  }

  // Errors during analysis
  if (result.errors && result.errors.length > 0) {
    sections.push(generateErrorsSection(result.errors));
  }

  // Footer
  sections.push('\n---');
  sections.push('*Generated by [RudderStack PR Reviewer](https://github.com/rudderlabs/pr-reviewer)*');

  return sections.join('\n\n');
}

/**
 * Generate summary section
 */
function generateSummary(result: AnalysisResult, sdkInfo?: { type: string; version?: string; methodCallsCount?: number; framework?: string }): string {
  const errors = result.issues.filter((i) => i.severity === 'error').length;
  const warnings = result.issues.filter((i) => i.severity === 'warning').length;
  const suggestions = result.issues.filter((i) => i.severity === 'suggestion').length;

  const lines: string[] = ['### 📊 Summary\n'];

  // SDK Information
  if (sdkInfo) {
    const sdkVersion = sdkInfo.version ? ` v${sdkInfo.version}` : '';
    const installType = sdkInfo.type.toUpperCase();
    lines.push(`**SDK:** RudderStack JavaScript SDK${sdkVersion} (${installType})`);

    if (sdkInfo.methodCallsCount !== undefined) {
      lines.push(`**Method Calls:** ${sdkInfo.methodCallsCount} SDK call${sdkInfo.methodCallsCount !== 1 ? 's' : ''} analyzed`);
    }

    if (sdkInfo.framework) {
      lines.push(`**Framework:** ${sdkInfo.framework}`);
    }

    lines.push('');
  }

  // Status indicator
  let statusIcon = '✅';
  let statusText = 'All checks passed';

  if (errors > 0) {
    statusIcon = '❌';
    statusText = `${errors} error${errors !== 1 ? 's' : ''} found`;
  } else if (warnings > 0) {
    statusIcon = '⚠️';
    statusText = `${warnings} warning${warnings !== 1 ? 's' : ''} found`;
  } else if (suggestions > 0) {
    statusIcon = '💡';
    statusText = `${suggestions} suggestion${suggestions !== 1 ? 's' : ''} available`;
  }

  lines.push(`${statusIcon} **${statusText}**\n`);

  // Issue breakdown
  const breakdown: string[] = [];
  if (errors > 0) breakdown.push(`❌ ${errors} Error${errors !== 1 ? 's' : ''}`);
  if (warnings > 0) breakdown.push(`⚠️ ${warnings} Warning${warnings !== 1 ? 's' : ''}`);
  if (suggestions > 0) breakdown.push(`💡 ${suggestions} Suggestion${suggestions !== 1 ? 's' : ''}`);

  if (breakdown.length > 0) {
    lines.push(`**Issues:** ${breakdown.join(' • ')}`);
  }

  return lines.join('\n');
}

/**
 * Generate files analyzed section
 */
function generateFilesSection(files: FileAnalysisInfo[]): string {
  const analyzedFiles = files.filter((f) => f.analyzed);
  const skippedFiles = files.filter((f) => !f.analyzed);
  const filesWithSDK = files.filter((f) => f.sdkDetected);

  const lines: string[] = ['### 📁 Files Analyzed\n'];

  lines.push(`**Analyzed:** ${analyzedFiles.length} file${analyzedFiles.length !== 1 ? 's' : ''}`);
  lines.push(`**With SDK Usage:** ${filesWithSDK.length} file${filesWithSDK.length !== 1 ? 's' : ''}`);

  if (skippedFiles.length > 0) {
    lines.push(`**Skipped:** ${skippedFiles.length} file${skippedFiles.length !== 1 ? 's' : ''}`);
  }

  return lines.join('\n');
}

/**
 * Generate issues section
 */
function generateIssuesSection(
  severity: 'error' | 'warning' | 'suggestion',
  issues: Issue[],
  collapsible: boolean
): string {
  const icon = severity === 'error' ? '❌' : severity === 'warning' ? '⚠️' : '💡';
  const title = severity === 'error' ? 'Errors' : severity === 'warning' ? 'Warnings' : 'Suggestions';

  const header = `### ${icon} ${title} (${issues.length})`;

  const content = issues
    .map((issue) => {
      const lines: string[] = [];

      // File and line
      const location = issue.line ? `${issue.file}:${issue.line}` : issue.file;
      lines.push(`**${location}**`);

      // Message
      lines.push(`${issue.message}`);

      // Impact
      if (issue.impact) {
        lines.push(`\n*Impact:* ${issue.impact}`);
      }

      // Fix suggestion
      if (issue.fix) {
        lines.push(`\n*Suggested fix:*\n\`\`\`javascript\n${issue.fix}\n\`\`\``);
      }

      // Confidence
      if (issue.confidence) {
        lines.push(`\n*Confidence:* ${issue.confidence}`);
      }

      return lines.join('\n');
    })
    .join('\n\n---\n\n');

  if (collapsible) {
    return `${header}\n\n<details>\n<summary>View details</summary>\n\n${content}\n\n</details>`;
  }

  return `${header}\n\n${content}`;
}

/**
 * Generate destination impacts section
 */
function generateDestinationImpactsSection(
  impacts: DestinationImpact[],
  collapsible: boolean
): string {
  const header = `### 🎯 Destination Impacts (${impacts.length})`;

  const content = impacts
    .map((impact) => {
      const icon = impact.severity === 'error' ? '❌' : impact.severity === 'warning' ? '⚠️' : '💡';

      const lines: string[] = [`${icon} **${impact.destinationName}** (${impact.destinationType})`];

      lines.push(`${impact.description}`);

      if (impact.affectedMappings && impact.affectedMappings.length > 0) {
        lines.push('\n**Affected Mappings:**');
        impact.affectedMappings.forEach((mapping) => {
          lines.push(`- \`${mapping.sourceProperty}\` → \`${mapping.destinationField}\`: ${mapping.impact}`);
        });
      }

      return lines.join('\n');
    })
    .join('\n\n');

  if (collapsible) {
    return `${header}\n\n<details>\n<summary>View details</summary>\n\n${content}\n\n</details>`;
  }

  return `${header}\n\n${content}`;
}

/**
 * Generate changes section
 */
function generateChangesSection(
  changes: ChangesSummary,
  includePropertyDetails: boolean,
  collapsible: boolean
): string {
  const header = '### 🔄 Changes Detected';

  const lines: string[] = [];

  // Added events
  if (changes.eventsAdded.length > 0) {
    lines.push('**Added Events:**');
    changes.eventsAdded.forEach((event) => {
      lines.push(`- \`${event.eventName}\` (${event.file}:${event.line})`);
    });
    lines.push('');
  }

  // Modified events
  if (changes.eventsModified.length > 0) {
    lines.push('**Modified Events:**');
    changes.eventsModified.forEach((event) => {
      lines.push(`- \`${event.eventName}\` (${event.file}:${event.line})`);
    });
    lines.push('');
  }

  // Removed events
  if (changes.eventsRemoved.length > 0) {
    lines.push('**Removed Events:**');
    changes.eventsRemoved.forEach((event) => {
      lines.push(`- \`${event.eventName}\` (${event.file}:${event.line})`);
    });
    lines.push('');
  }

  // Property changes
  if (includePropertyDetails && changes.propertyChanges.length > 0) {
    lines.push('**Property Changes:**');
    changes.propertyChanges.forEach((change) => {
      const changeDesc = getPropertyChangeDescription(change);
      lines.push(`- \`${change.eventName}.${change.propertyName}\`: ${changeDesc}`);
    });
  }

  const content = lines.join('\n');

  if (collapsible) {
    return `${header}\n\n<details>\n<summary>View details</summary>\n\n${content}\n\n</details>`;
  }

  return `${header}\n\n${content}`;
}

/**
 * Get property change description
 */
function getPropertyChangeDescription(change: {
  changeType: string;
  oldType?: string;
  newType?: string;
}): string {
  switch (change.changeType) {
    case 'added':
      return 'Added';
    case 'removed':
      return 'Removed';
    case 'type_changed':
      return `Type changed from ${change.oldType} to ${change.newType}`;
    case 'structure_changed':
      return 'Structure changed';
    default:
      return change.changeType;
  }
}

/**
 * Generate AI analysis section
 */
function generateAIAnalysisSection(insights: AIInsight[], collapsible: boolean): string {
  const header = `### 🤖 AI Analysis (${insights.length} insight${insights.length !== 1 ? 's' : ''})`;

  const content = insights
    .map((insight) => {
      const lines: string[] = [];

      if (insight.line) {
        lines.push(`**${insight.file}:${insight.line}**`);
      } else {
        lines.push(`**${insight.file}**`);
      }

      lines.push(insight.insight);

      if (insight.recommendations && insight.recommendations.length > 0) {
        lines.push('\n**Recommendations:**');
        insight.recommendations.forEach((rec) => {
          lines.push(`- ${rec}`);
        });
      }

      lines.push(`\n*Confidence: ${insight.confidence}*`);

      return lines.join('\n');
    })
    .join('\n\n---\n\n');

  if (collapsible) {
    return `${header}\n\n<details>\n<summary>View details</summary>\n\n${content}\n\n</details>`;
  }

  return `${header}\n\n${content}`;
}

/**
 * Generate errors section
 */
function generateErrorsSection(errors: string[]): string {
  const lines: string[] = ['### ⚠️ Analysis Errors\n'];

  lines.push('The following errors occurred during analysis:\n');

  errors.forEach((error) => {
    lines.push(`- ${error}`);
  });

  return lines.join('\n');
}

/**
 * Check if changes exist
 */
function hasChanges(changes: ChangesSummary): boolean {
  return (
    changes.eventsAdded.length > 0 ||
    changes.eventsModified.length > 0 ||
    changes.eventsRemoved.length > 0 ||
    changes.propertyChanges.length > 0
  );
}

/**
 * Generate progress comment (for updates)
 */
export function generateProgressComment(stage: string): string {
  return `## <img src="https://github.com/rudderlabs/pr-reviewer/raw/develop/icon.png" width="22" height="22" /> RudderStack Instrumentation Review

### ⏳ Analysis in Progress

Currently: ${stage}...

*This comment will be updated with results when analysis is complete.*`;
}

/**
 * Generate PR review comment body (for GitHub review submission)
 * This is the message that accompanies the review and inline comments
 */
export function generateReviewComment(result: AnalysisResult): string {
  const suggestions = result.issues.filter((i) => i.severity === 'suggestion');

  if (suggestions.length === 0) {
    return ''; // No review comment needed if no suggestions
  }

  const lines: string[] = [];

  lines.push('## 💡 Suggestions\n');
  lines.push('_Consider these improvements to enhance your tracking implementation:_\n');

  // Group suggestions by file
  const suggestionsByFile = new Map<string, typeof suggestions>();
  suggestions.forEach(s => {
    if (!suggestionsByFile.has(s.file)) {
      suggestionsByFile.set(s.file, []);
    }
    suggestionsByFile.get(s.file)!.push(s);
  });

  suggestionsByFile.forEach((fileSuggestions, file) => {
    lines.push(`### 📄 ${file}\n`);
    fileSuggestions.forEach(s => {
      lines.push(`**Line ${s.line}:** ${s.message}\n`);
      if (s.impact) {
        lines.push(`_Impact:_ ${s.impact}\n`);
      }
      if (s.fix) {
        lines.push('_Suggested fix:_');
        lines.push('```javascript');
        lines.push(s.fix);
        lines.push('```\n');
      }
    });
  });

  return lines.join('\n');
}
