/**
 * GitHub PR client for posting comments and annotations
 */

import * as github from '@actions/github';
import * as core from '@actions/core';
import type { SDKDetectionResult } from '../../core/sdk-detector';
import type { ValidationResult } from '../../core/api-validator';
import type { ChangeDetectionResult } from '../../core/change-detector';

export interface PRCommentOptions {
  owner: string;
  repo: string;
  pullNumber: number;
  token: string;
  pathPrefix?: string;
  commitSha?: string;
}

export interface InlineAnnotation {
  path: string;
  line: number;
  message: string;
  annotation_level: 'notice' | 'warning' | 'failure';
}

/**
 * Post simple comment when no SDK is detected
 */
export async function postNoSDKComment(options: PRCommentOptions): Promise<void> {
  const { owner, repo, pullNumber, token } = options;
  const octokit = github.getOctokit(token);

  const commentBody = `## <img src="https://github.com/rudderlabs/pr-reviewer/blob/test.sdk-changes-detection/icon.png?raw=true" alt="RudderStack" width="24" height="24" align="center"> RudderStack Instrumentation Review

### ℹ️ No RudderStack SDK instrumentation detected

If you're adding RudderStack JavaScript SDK for the first time, make sure to:
- Install the SDK via NPM: \`npm i @rudderstack/analytics-js --save-dev\`
- Or add the CDN loading snippet (refer to the source setup in RudderStack dashboard)

---
_🤖 Generated by [RudderStack PR Reviewer](https://github.com/rudderlabs/pr-reviewer)_`;

  const commentIdentifier = '<!-- rudderstack-pr-reviewer-analysis -->';
  const fullCommentBody = `${commentIdentifier}\n${commentBody}`;

  try {
    // Find existing comment
    const { data: comments } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: pullNumber,
    });

    const existingComment = comments.find((comment) => comment.body?.includes(commentIdentifier));

    if (existingComment) {
      // Update existing comment
      core.info(`Updating existing comment #${existingComment.id}`);
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingComment.id,
        body: fullCommentBody,
      });
    } else {
      // Create new comment
      core.info('Creating new PR comment');
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: pullNumber,
        body: fullCommentBody,
      });
    }

    core.info('✅ Successfully posted no-SDK comment');
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    core.warning(`Failed to post comment: ${errorMessage}`);
  }
}

/**
 * Format full analysis report with validation issues and changes
 */
export function formatAnalysisReport(
  sdkDetection: SDKDetectionResult,
  validation: ValidationResult,
  changes: ChangeDetectionResult,
  _options: { owner: string; repo: string; commitSha: string; pathPrefix?: string }
): string {
  let report = `## <img src="https://github.com/rudderlabs/pr-reviewer/blob/test.sdk-changes-detection/icon.png?raw=true" alt="RudderStack" width="24" height="24" align="center"> RudderStack Instrumentation Review

`;

  // Summary statistics
  report += '### 📊 Summary\n\n';

  // Changes section
  if (changes.isFirstTimeInstrumentation) {
    report += `✅ This PR adds RudderStack instrumentation for the first time. Found **${changes.addedCalls.length}** SDK method call(s).\n\n`;
  } else if (changes.hasChanges) {
    report += '🔄 Changes detected in the RudderStack instrumentation\n\n';
  }

  report += `JavaScript SDK is installed via ${sdkDetection.installationType === 'cdn' ? 'CDN snippet' : 'NPM package'} (v${sdkDetection.installationType === 'npm' ? sdkDetection.npmVersion : sdkDetection.cdnVersion})\n\n`;

  const totalIssues = validation.errors.length + validation.warnings.length + validation.suggestions.length;
  const statusEmoji = validation.errors.length > 0 ? '❌' : validation.warnings.length > 0 ? '⚠️' : '✅';

  report += `${statusEmoji} **${totalIssues}** issue(s) found\n\n`;
  report += `- ❌ **Errors:** ${validation.errors.length}\n`;
  report += `- ⚠️ **Warnings:** ${validation.warnings.length}\n`;
  report += `- 💡 **Suggestions:** ${validation.suggestions.length}\n\n`;

  if (totalIssues > 0) {
    report += '_See inline comments on the changed files for details._\n\n';
  }

  report += '---\n';
  report += '_🤖 Generated by [RudderStack PR Reviewer](https://github.com/rudderlabs/pr-reviewer)_\n';

  return report;
}

/**
 * Post or update PR comment with full analysis report
 */
export async function postAnalysisReport(
  sdkDetection: SDKDetectionResult,
  validation: ValidationResult,
  changes: ChangeDetectionResult,
  options: PRCommentOptions
): Promise<void> {
  const { owner, repo, pullNumber, token, pathPrefix } = options;
  const octokit = github.getOctokit(token);

  try {
    // Get PR to get commit SHA
    const { data: pr } = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: pullNumber,
    });

    const commitSha = pr.head.sha;

    const commentBody = formatAnalysisReport(sdkDetection, validation, changes, {
      owner,
      repo,
      commitSha,
      pathPrefix,
    });

    const commentIdentifier = '<!-- rudderstack-pr-reviewer-analysis -->';
    const fullCommentBody = `${commentIdentifier}\n${commentBody}`;

    // Find existing comment
    const { data: comments } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: pullNumber,
    });

    const existingComment = comments.find((comment) =>
      comment.body?.includes(commentIdentifier)
    );

    if (existingComment) {
      // Update existing comment
      core.info(`Updating existing analysis comment #${existingComment.id}`);
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingComment.id,
        body: fullCommentBody,
      });
    } else {
      // Create new comment
      core.info('Creating new analysis comment');
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: pullNumber,
        body: fullCommentBody,
      });
    }

    core.info('✅ Successfully posted analysis report');
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    core.warning(`Failed to post analysis report: ${errorMessage}`);
    throw error;
  }
}

/**
 * Post inline review comments to PR files (only for changed files)
 */
export async function postInlineAnnotations(
  annotations: InlineAnnotation[],
  options: PRCommentOptions
): Promise<void> {
  if (annotations.length === 0) {
    core.info('No inline annotations to post');
    return;
  }

  const { owner, repo, pullNumber, token } = options;
  const octokit = github.getOctokit(token);

  try {
    // Get PR files to see what's actually in the diff
    const { data: prFiles } = await octokit.rest.pulls.listFiles({
      owner,
      repo,
      pull_number: pullNumber,
    });

    const changedFiles = new Set(prFiles.map((f) => f.filename));

    core.info(`Changed files in PR: ${Array.from(changedFiles).join(', ')}`);
    core.info(`SDK locations to annotate: ${annotations.map(a => a.path).join(', ')}`);

    // Filter annotations to only include files that are in the PR diff
    const annotationsInDiff = annotations.filter((ann) => changedFiles.has(ann.path));

    if (annotationsInDiff.length === 0) {
      core.info('No SDK locations in changed files (see main comment for all locations)');
      return;
    }

    // Get the PR to get commit SHA
    const { data: pr } = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: pullNumber,
    });

    const commitSha = pr.head.sha;

    const commentIdentifier = '<!-- rudderstack-sdk-location -->';

    // Get existing review comments created by us to avoid duplicates
    const { data: existingComments } = await octokit.rest.pulls.listReviewComments({
      owner,
      repo,
      pull_number: pullNumber,
    });

    const ourExistingComments = existingComments.filter((comment) =>
      comment.body?.includes(commentIdentifier)
    );

    core.info(`Found ${ourExistingComments.length} existing SDK location comment(s)`);

    // Map existing comments by location for easy lookup
    const existingCommentsByLocation = new Map(
      ourExistingComments.map((c) => [`${c.path}:${c.line}`, c])
    );

    // Separate annotations into new and updates
    const newAnnotations: typeof annotationsInDiff = [];
    const updatedAnnotations: Array<{ ann: typeof annotationsInDiff[0]; existingComment: typeof ourExistingComments[0] }> = [];

    for (const ann of annotationsInDiff) {
      const location = `${ann.path}:${ann.line}`;
      const existingComment = existingCommentsByLocation.get(location);

      if (existingComment) {
        // Check if the message has changed
        const existingBody = existingComment.body?.replace(commentIdentifier + '\n', '') || '';
        if (existingBody !== ann.message) {
          updatedAnnotations.push({ ann, existingComment });
        }
      } else {
        newAnnotations.push(ann);
      }
    }

    if (newAnnotations.length === 0 && updatedAnnotations.length === 0) {
      core.info('All locations already have up-to-date comments');
      return;
    }

    core.info(`Creating ${newAnnotations.length} new comment(s), updating ${updatedAnnotations.length} existing comment(s)`);

    // Update existing comments individually (they're already posted, so we have to update them one by one)
    let updateCount = 0;
    for (const { ann, existingComment } of updatedAnnotations) {
      try {
        await octokit.rest.pulls.updateReviewComment({
          owner,
          repo,
          comment_id: existingComment.id,
          body: `${commentIdentifier}\n${ann.message}`,
        });
        updateCount++;
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        core.debug(`Could not update inline comment on ${ann.path}:${ann.line}: ${errorMessage}`);
      }
    }

    // Create a review with all new comments at once
    let createCount = 0;
    if (newAnnotations.length > 0) {
      try {
        const reviewComments = newAnnotations.map(ann => ({
          path: ann.path,
          line: ann.line,
          body: `${commentIdentifier}\n${ann.message}`,
        }));

        await octokit.rest.pulls.createReview({
          owner,
          repo,
          pull_number: pullNumber,
          commit_id: commitSha,
          event: 'COMMENT',
          comments: reviewComments,
        });

        createCount = newAnnotations.length;
        core.info(`✅ Submitted review with ${createCount} comment(s)`);
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        core.warning(`Failed to create review with comments: ${errorMessage}`);
        core.info('Falling back to individual comments...');

        // Fallback: Create comments individually if review fails
        for (const ann of newAnnotations) {
          try {
            await octokit.rest.pulls.createReviewComment({
              owner,
              repo,
              pull_number: pullNumber,
              body: `${commentIdentifier}\n${ann.message}`,
              commit_id: commitSha,
              path: ann.path,
              line: ann.line,
            });
            createCount++;
          } catch (individualError) {
            const individualErrorMessage = individualError instanceof Error ? individualError.message : String(individualError);
            core.debug(`Could not post inline comment on ${ann.path}:${ann.line}: ${individualErrorMessage}`);
          }
        }
      }
    }

    const totalSuccess = createCount + updateCount;
    if (totalSuccess > 0) {
      core.info(`✅ Posted ${createCount} new and updated ${updateCount} inline comment(s)`);
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    core.warning(`Failed to post inline annotations: ${errorMessage}`);
    // Don't throw - inline annotations are nice-to-have
  }
}
