import { createMockFileSystem } from '@tests/test.utils';
import { LockFileParser } from '../lock-file-parser';

describe('LockFileParser', () => {
  const config = {
    packageName: '@rudderstack/analytics-js',
    lockFiles: { npm: 'package-lock.json', yarn: 'yarn.lock', pnpm: 'pnpm-lock.yaml' },
  };

  describe('NPM lock file', () => {
    test('parses version from package-lock.json', async () => {
      const fs = createMockFileSystem({
        '/repo/package.json': JSON.stringify({
          name: 'test-app',
          version: '1.0.0',
          dependencies: {
            '@rudderstack/analytics-js': '^3.0.0',
          },
        }),
        '/repo/package-lock.json': JSON.stringify({
          packages: {
            'node_modules/@rudderstack/analytics-js': {
              version: '3.0.4',
            },
          },
        }),
      });
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBe('3.0.4');
    });

    test('returns null when package not found in package-lock.json', async () => {
      const fs = createMockFileSystem({
        '/repo/package.json': JSON.stringify({
          name: 'test-app',
          version: '1.0.0',
        }),
        '/repo/package-lock.json': JSON.stringify({
          packages: {},
        }),
      });
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBeNull();
    });
  });

  describe('Yarn lock file', () => {
    test('parses version from yarn.lock', async () => {
      const yarnLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@rudderstack/analytics-js@^3.0.0":
  version "3.0.4"
  resolved "https://registry.yarnpkg.com/@rudderstack/analytics-js/-/analytics-js-3.0.4.tgz#abc123"
  integrity sha512-abc123
`;
      const fs = createMockFileSystem({
        '/repo/package.json': JSON.stringify({
          name: 'test-app',
          version: '1.0.0',
          dependencies: {
            '@rudderstack/analytics-js': '^3.0.0',
          },
        }),
        '/repo/yarn.lock': yarnLock,
      });
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBe('3.0.4');
    });

    test('returns null when package not found in yarn.lock', async () => {
      const yarnLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"react@^18.0.0":
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#abc123"
  integrity sha512-abc123
`;
      const fs = createMockFileSystem({
        '/repo/package.json': JSON.stringify({
          name: 'test-app',
          version: '1.0.0',
          dependencies: {
            react: '^18.0.0',
          },
        }),
        '/repo/yarn.lock': yarnLock,
      });
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBeNull();
    });
  });

  describe('PNPM lock file', () => {
    test('parses version from pnpm-lock.yaml', async () => {
      const pnpmLock = `lockfileVersion: '6.0'

dependencies:
  '@rudderstack/analytics-js':
    specifier: ^3.0.0
    version: 3.0.4

packages:

  /@rudderstack/analytics-js@3.0.4:
    resolution: {integrity: sha512-abc123}
    dev: false
`;
      const fs = createMockFileSystem({
        '/repo/package.json': JSON.stringify({
          name: 'test-app',
          version: '1.0.0',
          dependencies: {
            '@rudderstack/analytics-js': '^3.0.0',
          },
        }),
        '/repo/pnpm-lock.yaml': pnpmLock,
      });
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBe('3.0.4');
    });

    test('returns null when no lock files exist', async () => {
      const fs = createMockFileSystem({});
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBeNull();
    });
  });

  describe('Lock file priority', () => {
    test('prefers package-lock.json over yarn.lock', async () => {
      const fs = createMockFileSystem({
        '/repo/package.json': JSON.stringify({
          name: 'test-app',
          version: '1.0.0',
          dependencies: {
            '@rudderstack/analytics-js': '^3.0.0',
          },
        }),
        '/repo/package-lock.json': JSON.stringify({
          packages: {
            'node_modules/@rudderstack/analytics-js': { version: '3.0.4' },
          },
        }),
        '/repo/yarn.lock': '@rudderstack/analytics-js@^3.0.0:\n  version "3.0.5"',
      });
      const parser = new LockFileParser(fs, config);

      const version = await parser.getVersion('/repo');

      expect(version).toBe('3.0.4');
    });
  });
});
